@Banking.API_HostAddress = https://localhost:7002

POST {{Banking.API_HostAddress}}/api/account/Create
Content-Type: application/json

{
  "UserId": 1
}

###

DELETE {{Banking.API_HostAddress}}/api/account/Delete/4

###

GET {{Banking.API_HostAddress}}/api/account/GetAll

###

GET {{Banking.API_HostAddress}}/api/account/GetById/3

###

GET {{Banking.API_HostAddress}}/api/account/GetDetailByCardNumber/43214321432143211

###

POST {{Banking.API_HostAddress}}/api/user/Create
Content-Type: application/json

{
  "Name": "Kiril",
  "LastName": "Sudakov",
  "Birthday": "2010-11-16T12:06:16.094Z",
  "Phone": "+380977600280"
}

###

GET {{Banking.API_HostAddress}}/api/user/GetById/3

###

POST {{Banking.API_HostAddress}}/api/transactiontype/Create
Content-Type: application/json

{
  "Name": "test"
}

###

DELETE {{Banking.API_HostAddress}}/api/transactiontype/Delete/5

###

GET {{Banking.API_HostAddress}}/api/transactiontype/GetAll

###

GET {{Banking.API_HostAddress}}/api/transactiontype/GetById/6

###

PUT {{Banking.API_HostAddress}}/api/transactiontype/Update/6
Content-Type: application/json

{
  "Name": "testUp"
}

###


POST {{Banking.API_HostAddress}}/api/transaction/Deposit
Content-Type: application/json

{
  "Amount": 52000,
  "ToAccountId": 2
}

###

GET {{Banking.API_HostAddress}}/api/transaction/GetAll

###

GET {{Banking.API_HostAddress}}/api/transaction/GetById/5

###

POST {{Banking.API_HostAddress}}/api/transaction/Withdraw
Content-Type: application/json

{
  "Amount": -55000,
  "ToAccountId": 2
}

###

POST {{Banking.API_HostAddress}}/api/transaction/Transfer
Content-Type: application/json

{
  "Amount": -150000,
  "FromAccountId": 2,
  "ToAccountId": 15
}

###
